### ISSUE TITLE
Fields do not appear

### ISSUE THREAD

**Issue by mrprkr** [Diyzzuf/grav-plugin-private#11]
I've created a new clean build of grav and added this plugin. Once it's enabled the login page loads but no password field is visible. 

![screen shot 2015-10-28 at 5 30 49 pm](https://cloud.githubusercontent.com/assets/6835002/10781245/a5fd1526-7d99-11e5-9a6f-2a1793ab94b7.png)

**Comment by TribuneX** [comment]
Same for me. I do not get any field to enter a password

**Comment by ahmadassaf** [comment]
@mrprkr @TribuneX this is most probably due to the fact that the private login template is not rendered correctly (duplicate to #9 )

To resolve this for the moment rename the template in `user/plugins/private/templates` to something like `login-private.html.twig`. 

Then you will need to tell the `login.md` to use that template for rendering. You do this by changing that in the `user/plugins/private/pages/login.md`

```
---
title: Login
slug: login
robots: noindex,nofollow
template: login-private
---
```
