### ISSUE TITLE
Successful login not redirecting to page

### ISSUE THREAD

**Issue by trst** [Diyzzuf/grav-plugin-private#14]
I have the plugin set to keep one page of my site private using the tag `hidden`, however, even after entering the password correctly I am not redirected to the page. Have I missed some step?
1. I've created a long salt
2. I've set a new SHA1 password
3. The plugin is enabled
4. I have the plugin set to `no_user`

I've attached a screenshot of the private.yaml file

Thoughts?

![screen shot 2016-02-16 at 17 47 16](https://cloud.githubusercontent.com/assets/1895782/13085285/55611a8e-d4d5-11e5-98df-6c2616f0603b.png)

**Comment by Diyzzuf** [comment]
I don’t see an error..
It's just the redirection that doesn't works ? Or login step too ?

Can you debug $_SESSION for checking it’s works ?

And.. Maybe, change the security salt `session_ss` with an alphanumeric string. ( alphanumeric « Good for Cakephp Security Salt ») I’ve already had this problem.

**Comment by Endogen** [comment]
Since this is an old post and i have the exact same issue, i guess it's ok to write it down here :)
I can enter the password and it is for sure correct because if i set the route to "/admin" it works and redirects me to the admin panel.
But when i enter another route, for example "/private" (that is the same page that i opened up to enter the password) then the main page gets loaded.

I think this has something todo with the route but since i'm not really experienced with PHP and Grav, i can't tell what i'm doing wrong. I'm using Grav 1.1.0-rc.2 and the blog-skeleton.

**Comment by Diyzzuf** [comment]
The private plugin has no relation with the Admin Plugin.
Moreover , it's even disabled for Admin Plugin.
The 2 plugins are dissociated, and passwords are differents.

You enter the good password for the Private Plugin ? On the config file of Private Plugin ?

**Comment by Endogen** [comment]
I enter the good password on the "private" page (http://www.somedomain.com/private) and i would expect that after the good password was entered, i see the content of that page (in config the route for login is "/private"). But that doesn't happen. If i enter "/admin" in the config, i get redirected to http://www.somedomain.com/admin and that is the admin-plugin. So that works. But any other route, any other page, doesn't.

**Comment by Diyzzuf** [comment]
I failed to recreate this bug.
Can you post me your config ?

**Comment by Endogen** [comment]
Sure, thanks for looking into this

```
enabled: true

routes:
  login: "/private"
  logout: "/logout"

session_ss: s!Qrqf-cJZwVl@u*AY^TuG9Ku*g3yNPH

private_site: false
private_tag: hidden
enable_username: false

users:
  no_user : 8c00293828a35ac41bbf876a42251b2b0dd3edaf

texts:
  h1 : Private Area
  h2 : Please <strong>login</strong> to view this content
fields:
  username:
    label: "Username"
    placeholder: "Enter your username"
  password:
    label: "Password"
    placeholder: "Enter your password"
  antispam:
    label: "Antispam"
    placeholder: "Please leave this field empty for Antispam"
  login:
    label: "Login"
messages:
  success: "You are logged."
  error: "Oops! There was a problem with your submission. Please try again or <a href='https://github.com/Diyzzuf/grav-plugin-private/issues' target='_blank'>report an issue </a>"
  fail: "Oops! Something went wrong.. Try Again !"
```

**Comment by Diyzzuf** [comment]
Ok i see.
Session_ss **MUST BE** an **Alphanumeric** string, whitout special char, like `ubANQBYL7bIxzebVwguy2t4c2ZxJZlqz` I've forgot this on the doc.
For the moment, Sethcardoza is down, but you can use the [cache version](http://webcache.googleusercontent.com/search?q=cache:www.sethcardoza.com/tools/random-password-generator/), and go to the Alphanumeric Part.

Sorry for this inconvenient

**Comment by Endogen** [comment]
I have changed the session_ss to alphanumeric but it still redirects me to the blog `http://www.domain.com/blog` which is the main page and not the `http://www.domain.com/private` page. Can i send you my grav installation so that you can take a look at it?

**Comment by Diyzzuf** [comment]
Your main page `http://www.domain.com/blog` have the `hidden` tag ?
Yes, exceptionally you can send me. (Or create a project on github, and send the link. Must easy for me )

**Comment by Endogen** [comment]
No my main page does not have the `hidden` tag. Here is the project https://github.com/Endogen/Testing

**Comment by Diyzzuf** [comment]
**EDIT : Removed because it's a bad fix !**

> Ok. Can you test to add
> `$_SESSION['referer_redirect'] = $this->uri->path();` to the line `126` of `private.php`.
> Normaly, that fix the bug, and it's an oversight on my part.
> 
> ( I've created a pull request on your project )

**Comment by Endogen** [comment]
Nope, doesn't work. Same situation as before

**Comment by Diyzzuf** [comment]
Sorry, I have editing the wrong line. New Pull

**Comment by Endogen** [comment]
Still not working. I always get redirected to `/blog`

**Comment by Diyzzuf** [comment]
what would you attempt to do ?
Set all website private ? Or just blog ? Or other ?
The login form works ? Or you have an error ?
After login, you want to redirect to Home ? Blog ? History page ?

**Comment by Endogen** [comment]
I would like to have: one page with the name "private". After opening that page i would like to see the login form (all this works fine already). Now here is what is not working: after i enter the correct password i would like to see the content of the "private" page. What happens now is: after entering the correct password i get redirected to my main page ("www.domain.com/blog"). The main page is a blog page. But i dont understand why i get redirected to "/blog". I would expect to be redirected to "/private".

I only want to have one page private. The page is called "private" the URL path is "www.domain.com/private"

Yes the loginform works. I dont get any error. I only get redirected to the wrong page.

I want to get redirected to "www.domain.com/private"

**Comment by Diyzzuf** [comment]
Ok !
A confusing use of the plugin.
If you whant to make a page private, take it the `hidden` tag. And make it this page on the menu.
If an user is not logged, and he click on this link, it's auto-redirected on the login form, in url `login` ( or the url configured on login route ). All pages with `hidden` tag are redirected on the `private` login page.

That's all.
Make a page with `hidden` tag on the menu. ( But not the same route for the `private` page and the `login` form page.

**Comment by Endogen** [comment]
What i want is not really confusing, it's very simple :) I want a page in Grav that is password protected and when i access the page i get a login screen where i can enter the password and when the password was correctly entered i want to see the content of the protected page. That's the use case but it still doesn't really work.

Everything works except the redirecting to the protected page after i enter the correct password. I always get redirected to the main page after i enter the password correctly... I tried it with your fixed and without. Is there somewhere a working example that i can look at? Otherwise i think i can't use it as it is.

**Comment by Diyzzuf** [comment]
Ok; by default :
`private` is the plugin.
`/login` is the url for displaing the login form.
`/myprivatepage` is the url of page that i want to private, with the `hidden` tag
`/myotherprivatepage` is the url of the second page that i want to private, with the `hidden` tag

In your case
`/private` is YOUR url for display the login form
`/private` is YOUR page that you want to private. ( Slug Page )
It's a conflict on this 2 slug, because same slug, same path, same url..

2 solutions : 
- Change the Name and Slug of your page
  or
- Change the url of the login form on the private plugin config

**Comment by Endogen** [comment]
I understood from your previous post that i made the mistake that both pages (login & private page) had the same name. So then i changed it so that these were two different pages and it still didn't work. Sorry but i guess the plugin is not for me :)

But thanks for you patience and help!

**Comment by Diyzzuf** [comment]
No problems ;)
