### ISSUE TITLE
Exclude pages from Private

### ISSUE THREAD

**Issue by steveglachan** [Diyzzuf/grav-plugin-private#17]
Is there a way to set the site to private but exclude a few select pages and have them public?

**Comment by Diyzzuf** [comment]
No option for this, sorry..
Just put the site public, add the private tag to all pages, except few selected page

**Comment by paulcmal** [comment]
How about, instead of using a "hidden" tag, using a taxonomy called `access` with usual values `public` and `private`?

I think that would be an elegant way to handle this use-case (using private site with `access: public` taxonomy and vice-versa).

But it would also tackle [this issue](https://github.com/getgrav/grav-plugin-taxonomylist/issues/10) (which is what brought me here in the first place).

Also, this would allow to use more parameters than just "public" and "private", for example to build group access rules or any kind of ACL.

What do you think?

**Comment by Diyzzuf** [comment]
I think it's a good idea, and It was the future of the plugin.. but... it's a future implementation for the payed version of Admin plugin.. In this case, I can't upgrade this plugin , or add ACL ..  :/ Sorry.

**Comment by paulcmal** [comment]
> but... it's a future implementation for the payed version of Admin plugin..

What do you mean? You are planning on developing this as a paid plugin? Or are you pointing out that advanced management will be provided by default as a paid plugin?

I think it wouldn't be so hard to interact with the login plugin to use a custom field like `groups` in user date, then when a page is processed, check that either page is public, or user is logged in then match user groups to an `access` taxonomy set to `group_GROUPNAME`.

So that you could have a page like:

```
title: Our secret page
slug: test
taxonomy:
  access: group_accomplices group_friends
```

And that would give access to all users in those groups.

The base block for any further research on this would be in my opinion to have this plugin deploy its own taxonomy. Would you hypothetically accept PRs on this if I ever have time to dig into it?

**Comment by Diyzzuf** [comment]
> What do you mean? You are planning on developing this as a paid plugin? Or are you pointing out that advanced management will be provided by default as a paid plugin?

Yes, it's a default feature on the paid Admin plugin. And... set a page to private, too. Bad news for my plugin and development/enhancement of it.

The worst is that I had already written parts of the new release :/ With integration in Admin plugin, Create Users, Acl.. :/

Sorry for this inconvenient, i can't .... ?overrides? plans of the Grav Staff.

**Comment by paulcmal** [comment]
Could we still at least change the default taxonomy to access to fix this bug and https://github.com/getgrav/grav-plugin-taxonomylist/issues/10 ?

Could we maybe talk about it on Gitter / IRC / Jabber?

**Comment by bobrocke** [comment]
@Diyzzuf On the Grav Slack channel, the Grav guys don't think the Admin Pro plug-in will have features competing with this. Would you check with your contacts again, to be sure?

**Comment by Diyzzuf** [comment]
Indeed, I have just read the conversation.
Maybe, their plans have changed since 2015.

**I haven't got the time to develop this yet**, but I will try to make a new release, with Admin Panel. ( Perhaps include Grav ACL, Groups etc.. )

**Comment by Diyzzuf** [comment]
Beta tester of new release ? ( not on production )
https://github.com/Diyzzuf/grav-plugin-private-site

Requires Login, Form, Email plugins, and integrated with Admin plugin, on Page=>Options.

Adding and Managing user : https://learn.getgrav.org/admin-panel/faq#adding-and-managing-users
ACL : https://learn.getgrav.org/advanced/groups-and-permissions
Allow User Registration : https://github.com/getgrav/grav-plugin-login/blob/develop/README.md#allow-user-registration
